# 最后更新：2023.06.30
# 说明：自用超精简 Quantumult X 配置文件。适用于 v1.0.30-。更新版本建议使用 mini+ 配置文件
# 图标库（彩）
# 1.「Koolson」QureColor
# https://github.com/Koolson/Qure/raw/master/Other/QureColor.json
# 2.「Orz-3」miniColor
# https://raw.githubusercontent.com/Orz-3/mini/master/miniColor.json
# 3.「Orz-3」mini+
# https://raw.githubusercontent.com/Orz-3/mini/master/mini%2B.json
# 4.「shindgewongxj」WHATSINStash
# https://raw.githubusercontent.com/shindgewongxj/WHATSINStash/main/icon/iconset.json
# 5. 各大机场
# https://raw.githubusercontent.com/Twoandz9/TheMagic-Icons/main/TheRaw.json
# GeoLite2 源
# https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb

[general]
# 远程配置文件图标
profile_img_url = https://github.githubassets.com/images/modules/site/integrators/google.png
# 资源解析器
resource_parser_url = https://raw.fastgit.org//KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js
network_check_url = http://bing.com
server_check_url = http://1.1.1.1
# 服务器信息展示
geo_location_checker = http://ip-api.com/json/?lang=zh-CN, https://raw.githubusercontent.com/MingdeCZ/OutSide-Reborn/main/QuantumultX/Scripts/ip-api.js
udp_whitelist = 53, 80-427, 444-65535
excluded_routes = 10.0.0.0/8, 100.64.0.0/ 10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32

[dns]
;no-system
no-ipv6
# 常规 DNS
# 腾讯
server = 119.29.29.29
server = 119.28.28.28
# 阿里
server = 223.5.5.5
# 114
server = 114.114.114.114
# 制定域名解析 DNS
server = /*.taobao.com/223.5.5.5
server = /*.tmall.com/223.5.5.5
server = /*.alipay.com/223.5.5.5
server = /*.aliyun.com/223.5.5.5
server = /*.jd.com/119.28.28.28
server = /*.qq.com/119.28.28.28
server = /*.tencent.com/119.28.28.28
server = /*.weixin.com/119.28.28.28
server = /*.bilibili.com/119.29.29.29
server = /*.netease.com/119.29.29.29

[policy]
[server_local]
[server_remote]
[filter_local]
# 哔哩哔哩(白图标外区版)港澳台番剧自动切换地区 & 显示豆瓣评分
ip-cidr, 203.107.1.1/24, reject
geoip, cn, direct
final, proxy

[filter_remote]
https://raw.githubusercontent.com/MingdeCZ/OutSide-Reborn/main/QuantumultX/Rules/Apple.list, tag=苹果, force-policy=direct, update-interval=172800, opt-parser=false, enabled=true
https://raw.githubusercontent.com/MingdeCZ/OutSide-Reborn/main/QuantumultX/Rules/ChinaMax.list, tag=国内合集, force-policy=direct, update-interval=172800, opt-parser=false, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Proxy/Proxy.list, tag=代理, force-policy=proxy, update-interval=172800, opt-parser=false, enabled=true

[rewrite_local]
[rewrite_remote]
https://raw.githubusercontent.com/MingdeCZ/OutSide-Reborn/main/QuantumultX/Rewrites/lite.conf, tag=lite, update-interval=172800, opt-parser=false, enabled=true

[task_local]
event-interaction https://raw.githubusercontent.com/MingdeCZ/OutSide-Reborn/main/QuantumultX/Scripts/streaming-ui-check.js, tag=解锁检测, img-url=checkmark.seal.fill.system, enabled=true

[http_backend]
[mitm]
skip_validating_cert = true
