log-level: warning
hosts:
  ip6-localhost: "::1"
  ip6-loopback: "::1"
  ip6-localnet: "fe00::0"
  ip6-mcastprefix: "ff00::0"
  ip6-allnodes: "ff02::1"
  ip6-allrouters: "ff02::2"
  ip6-allhosts: "ff02::3"
  doh.pub: "1.12.12.12"
  dot.pub: "1.12.12.12"
  doh.360.cn: "23.6.48.18"
  dot.360.cn: "101.198.198.198"
  services.googleapis.cn: "74.125.193.94"
  talk.google.com: "108.177.125.188"
  mtalk.google.com: "108.177.125.188"
  alt1-mtalk.google.com: "3.3.3.3"
  alt2-mtalk.google.com: "3.3.3.3"
  alt3-mtalk.google.com: "74.125.200.188"
  alt4-mtalk.google.com: "74.125.200.188"
  alt5-mtalk.google.com: "3.3.3.3"
  alt6-mtalk.google.com: "3.3.3.3"
  alt7-mtalk.google.com: "74.125.200.188"
  alt8-mtalk.google.com: "3.3.3.3"
dns:
  enable: true
  nameserver:
    - https://223.5.5.5/dns-query#h3=true
    - 119.29.29.29
  nameserver-policy:
    "blog.google,googletraveladservices.com,dl.google.com,dl.l.google.com,clientservices.googleapis.com,update.googleapis.com,fonts.googleapis.com,fonts.gstatic.com": "119.29.29.29"
    "www.miwifi.com,miwifi.com,tplogin.cn,tplinklogin.net,tplinkwifi.net": system
    "networking.apple,+.icloud.com": https://doh.dns.apple.com/dns-query
    "+.tencent.com,+.qcloud.com,+.qcloudcdn.cn,+.qcloudcdn.com,+.qcloudcos.com,+.qcloudimg.com,+.qcloudimg.com,+.qcloudcjgj.com,+.qcloudwzgj.com,+.qcloudzygj.com,+.myqcloud.com,+.tencent-cloud.net,+.tencentcloud-aiot.com,+.tencentcloudapi.com,+.tencentcloudcr.com,+.tencentcloudmarket.com,+.qq.com,+.qlogo.cn,+.qpic.cn,+.weixin.qq.com,+.wx.qq.com,+.weixin.com,+.weixinbridge.com,+.wechat.com,+.servicewechat.com,+.weiyun.com,+.gtimg.cn,+.idqqimg.com,+.cdn-go.cn,+.smtcdns.com,+.smtcdns.net,url.cn,upos-sz-mirrorcos.bilivideo.com,upos-sz-mirrorcos?.bilivideo.com,upos-sz-mirrorcos??.bilivideo.com,upos-sz-upcdntx.bilivideo.com": https://doh.pub/dns-query
    "+.baidu,+.baidu.com,+.bdimg.com,+.bdstatic.com,+.baidupcs.+,+.baiduyuncdn.+,+.baiduyundns.+,+.bdydns.+,+.bdycdn.+,+.bdysite.com,+.bdysites.com,+.baidubce.+,+.bcedns.+,+.bcebos.com,+.bcevod.com,+.bceimg.com,+.bcehost.com,+.bcehosts.com,dwz.cn,upos-sz-mirrorbos.bilivideo.com,upos-sz-upcdnbd??.bilivideo.com": "180.76.76.76"
    "+.360.cn,+.360safe.com,+.360kuai.com,+.so.com,+.360webcache.com,+.qihuapi.com,+.qhimg.com,+.qhimgs.com,+.qhimgs?.com,+.qhmsg.com,+.qhres.com,+.qhres?.com,+.dhrest.com,+.qhupdate.com,+.yunpan.cn,+.yunpan.com.cn,+.yunpan.com,urlqh.cn": https://doh.360.cn/dns-query
    "+.amemv.com,+.bdxiguaimg.com,+.bdxiguastatic.com,+.byted-static.com,+.bytedance.+,+.bytedns.net,+.bytednsdoc.com,+.bytegoofy.com,+.byteimg.com,+.bytescm.com,+.bytetos.com,+.bytexservice.com,+.douyin.com,+.douyinpic.com,+.douyinstatic.com,+.douyinvod.com,+.feelgood.cn,+.feiliao.com,+.gifshow.com,+.huoshan.com,+.huoshanzhibo.com,+.ibytedapm.com,+.iesdouyin.com,+.ixigua.com,+.kspkg.com,+.pstatp.com,+.snssdk.com,+.toutiao.com,+.toutiao13.com,+.toutiao???.???,+.toutiaocloud.cn,+.toutiaocloud.com,+.toutiaopage.com,+.wukong.com,+.zijieapi.com,+.zijieimg.com,+.zjbyte.com,+.zjcdn.com": "180.184.1.1"
    "+.gov.cn": "1.2.4.8"
geox-url:
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://github.com/Masaiki/GeoIP2-CN/raw/release/Country.mmdb"
rules:
  - DOMAIN,httpdns.alicdn.com,REJECT
  - DOMAIN,httpdns-api.aliyuncs.com,REJECT
  - DOMAIN,httpdns-sc.aliyuncs.com,REJECT
  - IP-CIDR,203.107.1.0/24,REJECT,no-resolve
  - DOMAIN,httpsdns.baidu.com,REJECT
  - DOMAIN,httpdns.baidu.com,REJECT
  - DOMAIN,httpdns.baidubce.com,REJECT
  - IP-CIDR,180.76.76.200/32,REJECT,no-resolve
#  - DOMAIN,httpdns.bilivideo.com,REJECT
  - DOMAIN,httpdns.c.cdnhwc2.com,REJECT
  - DOMAIN,dns.jd.com,REJECT
  - IP-CIDR,101.124.19.122/32,REJECT,no-resolve
  - IP-CIDR6,2402:db40:5100:1011::5/128,REJECT,no-resolve
  - IP-CIDR,103.224.222.208/32,REJECT,no-resolve
  - DOMAIN,httpdns.calorietech.com,REJECT
  - DOMAIN,httpdns.meituan.com,REJECT
  - IP-CIDR,202.90.108.13/32,REJECT,no-resolve
  - IP-CIDR,202.90.110.46/32,REJECT,no-resolve
  - DOMAIN,httpdns.yunxindns.com,REJECT
  - DOMAIN,httpdns.n.netease.com,REJECT
  - DOMAIN,httpdns.music.163.com,REJECT
  - DOMAIN,music.httpdns.c.163.com,REJECT
  - DOMAIN,lofter.httpdns.c.163.com,REJECT
  - IP-CIDR,59.111.239.61/32,REJECT,no-resolve
  - IP-CIDR,59.111.239.62/32,REJECT,no-resolve
  - IP-CIDR,115.236.121.51/32,REJECT,no-resolve
  - IP-CIDR,115.236.121.195/32,REJECT,no-resolve
  - DOMAIN-SUFFIX,httpdns.pro,REJECT
  - IP-CIDR,119.29.29.98/32,REJECT,no-resolve
  - IP-CIDR,119.29.29.99/32,REJECT,no-resolve
  - DOMAIN,httpdns.volcengineapi.com,REJECT
  - DOMAIN,dns.weibo.cn,REJECT
  - IP-CIDR,39.97.128.148/32,REJECT,no-resolve
  - IP-CIDR,39.97.130.51/32,REJECT,no-resolve
  - DOMAIN,dns.weixin.qq.com,REJECT
  - DOMAIN,dns.weixin.qq.com.cn,REJECT
  - IP-CIDR,42.81.232.18/32,REJECT,no-resolve
  - IP-CIDR,42.187.182.106/32,REJECT,no-resolve
  - IP-CIDR,42.187.182.123/32,REJECT,no-resolve
  - IP-CIDR,42.187.184.154/32,REJECT,no-resolve
  - IP-CIDR,123.151.54.50/32,REJECT,no-resolve
  - IP-CIDR6,2402:4e00:1900:1700:0:9554:1ad9:c3a/128,REJECT,no-resolve
  - IP-CIDR6,240e:928:1400:10::25/128,REJECT,no-resolve
  - IP-CIDR,182.254.116.117/32,REJECT,no-resolve
  - IP-CIDR,182.254.118.119/32,REJECT,no-resolve
  - IP-CIDR,118.89.204.198/32,REJECT,no-resolve
  - IP-CIDR6,2402:4e00:1200:ed00:0:9089:6dac:96b6/128,REJECT,no-resolve
#  - DOMAIN-SUFFIX,doubleclick-cn.net,REJECT
#  - DOMAIN-SUFFIX,doubleclick.net,REJECT
  - DOMAIN-SUFFIX,wxs.qq.com,REJECT
  - DOMAIN,wxsmsdy.video.qq.com,REJECT
  - DOMAIN,ad.maoyan.com,REJECT
  - DOMAIN,ca.iadsdk.apple.com,DIRECT
#  - DOMAIN-SUFFIX,iadsdk.apple.com,REJECT
  - DOMAIN,lookup.api.bsb.baidu.com,REJECT
  - DOMAIN-SUFFIX,u3.ucweb.com,REJECT
  - DOMAIN-KEYWORD,safebrowsing.,REJECT
  - AND,((DOMAIN-KEYWORD,-ad-),(DOMAIN-SUFFIX,byteimg.com)),REJECT
  - AND,((DOMAIN-KEYWORD,-ttam-),(DOMAIN-SUFFIX,ibyteimg.com)),REJECT
  - AND,((DOMAIN-KEYWORD,ssdk-),(DOMAIN-SUFFIX,pangle.io)),REJECT
  - AND,((DOMAIN-KEYWORD,pangolin),(DOMAIN-SUFFIX,sgsnssdk.com)),REJECT
  - AND,((DOMAIN-KEYWORD,lf),(DOMAIN-KEYWORD,-short.bytetos.com)),REJECT
  - AND,((DOMAIN-KEYWORD,v),(DOMAIN-KEYWORD,-be-pack.pglstatp-toutiao.com)),REJECT
  - AND,((DOMAIN-KEYWORD,sf),(DOMAIN-KEYWORD,-be-pack.pglstatp-toutiao.com)),REJECT
  - AND,((DOMAIN-KEYWORD,s),(DOMAIN-KEYWORD,-fe-scm.pglstatp-toutiao.com)),REJECT
  - AND,((DOMAIN-KEYWORD,sf),(DOMAIN-KEYWORD,-ttcdn-tos.pstatp.com)),REJECT
  - AND,((DOMAIN-KEYWORD,sf),(DOMAIN-KEYWORD,-fe-tos.pglstatp-toutiao.com)),REJECT
  - AND,((DOMAIN-KEYWORD,sf),(DOMAIN-KEYWORD,-static.i18n-pglstatp.com)),REJECT
  - AND,((DOMAIN-KEYWORD,if),(DOMAIN-KEYWORD,-cdn-tos.bytescm.com)),REJECT
  - AND,((DOMAIN-KEYWORD,if),(DOMAIN-KEYWORD,-analytics.bytescm.com)),REJECT
  - AND,((DOMAIN-KEYWORD,lf),(DOMAIN-KEYWORD,-analytics.bytescm.com)),REJECT
  - AND,((DOMAIN-KEYWORD,ads),(DOMAIN-KEYWORD,normal),(DOMAIN-SUFFIX,zijieapi.com)),REJECT
  - AND,((DOMAIN-KEYWORD,api),(DOMAIN-KEYWORD,-access-),(DOMAIN-SUFFIX,pangle.io)),REJECT
  - AND,((DOMAIN-KEYWORD,api),(DOMAIN-KEYWORD,-log-),(DOMAIN-SUFFIX,pangle.io)),REJECT
  - AND,((DOMAIN-KEYWORD,api),(DOMAIN-KEYWORD,-dual-event-),(DOMAIN-SUFFIX,pangle.io)),REJECT
  - AND,((DOMAIN-KEYWORD,api),(DOMAIN-KEYWORD,pangolin),(DOMAIN-SUFFIX,sgsnssdk.com)),REJECT
  - AND,((DOMAIN-KEYWORD,ads),(DOMAIN-KEYWORD,-normal-lq),(DOMAIN-SUFFIX,zijieapi.com)),REJECT
  - DOMAIN-REGEX,^http:\/\/p\d+-be-pack-sign\.pglstatp-toutiao\.com\/(ad-app-package|web\.business\.image)\/,REJECT
#  - DOMAIN,mon.zijieapi.com,REJECT
  - DOMAIN,lf-ad-ies.bytecdn.cn,REJECT
  - DOMAIN,i.snssdk.com,REJECT
  - DOMAIN,is.snssdk.com,REJECT
  - DOMAIN,bds.snssdk.com,REJECT
  - DOMAIN,dm.bytedance.com,REJECT
  - DOMAIN,dm.pstatp.com,REJECT
#  - DOMAIN,dm.toutiao.com,REJECT
#  - DOMAIN,log.snssdk.com,REJECT
  - DOMAIN,s3a.pstatp.com,REJECT
  - DOMAIN,sdfp.snssdk.com,REJECT
  - DOMAIN,tosv.boe.byted.org,REJECT
  - DOMAIN,tosv.byted.org,REJECT
  - DOMAIN,extlog.snssdk.com,REJECT
  - DOMAIN,mssdk-bu.bytedance.com,REJECT
#  - DOMAIN,toblog.ctobsnssdk.com,REJECT
  - DOMAIN,mssdk.volces.com,REJECT
  - DOMAIN,pangolin.snssdk.com,REJECT
  - DOMAIN,gromore.pangolin-sdk-toutiao.com,REJECT
  - DOMAIN,ether-pack.pangolin-sdk-toutiao.com,REJECT
  - DOMAIN-KEYWORD,-ad-sign.byteimg.com,REJECT
  - DOMAIN-KEYWORD,api-access.pangolin-sdk-toutiao,REJECT
  - DOMAIN-KEYWORD,log-api.pangolin-sdk-toutiao,REJECT
  - DOMAIN-KEYWORD,-ad.byteoversea.com,REJECT
  - DOMAIN-KEYWORD,video-cn.snssdk.com,REJECT
  - DOMAIN-KEYWORD,asiad.byteactivity,REJECT
  - DOMAIN-KEYWORD,iflyad.bj.openstorage.cn,REJECT
  - DOMAIN-KEYWORD,bjimp.voiceads.cn,REJECT
  - DOMAIN,sdk.1rtb.net,REJECT
  - DOMAIN,cdn.1rtb.com,REJECT
  - DOMAIN,adx.halomobi.com,REJECT
  - DOMAIN,api.htp.hubcloud.com.cn,REJECT
  - DOMAIN,res1.hubcloud.com.cn,REJECT
  - DOMAIN,sdktmp.hubcloud.com.cn,REJECT
  - DOMAIN,v.adx.hubcloud.com.cn,REJECT
#  - DOMAIN,config.inmobi.cn,REJECT
  - DOMAIN,ztoken.uyunad.com,REJECT
  - DOMAIN,aaid.uyunad.com,REJECT
  - DOMAIN,yumao.puata.info,REJECT
#  - DOMAIN,gdfp.gifshow.com,REJECT
#  - DOMAIN,open.e.kuaishou.com,REJECT
  - DOMAIN,adtrack.e.kuaishou.com,REJECT
  - DOMAIN-SUFFIX,adukwai.com,REJECT
#  - DOMAIN,init.supersonicads.com,REJECT
  - DOMAIN,st.appsad.cn,REJECT
  - DOMAIN,sdk.beizi.biz,REJECT
  - DOMAIN,api-htp.beizi.biz,REJECT
#  - DOMAIN,admaster.com.cn,REJECT
#  - DOMAIN-SUFFIX,miaozhen.com,REJECT
  - DOMAIN-SUFFIX,admobile.top,REJECT
  - DOMAIN,api-c.dutils.com,REJECT
  - DOMAIN,api-d.dutils.com,REJECT
  - DOMAIN,api-p0.yksdks.com,REJECT
  - DOMAIN,cache-verify.dutils.com,REJECT
  - DOMAIN,cdn-api-verify.dutils.com,REJECT
  - DOMAIN,devs-data.dutils.com,REJECT
  - DOMAIN,log-verify.dutils.com,REJECT
  - DOMAIN,m.mpl.dutils.com,REJECT
#  - DOMAIN,api.share.mob.com,REJECT
  - DOMAIN,api.verify.mob.com,REJECT
#  - DOMAIN,log-verify.mob.com,REJECT
  - DOMAIN,sdk.push.mob.com,REJECT
  - DOMAIN-SUFFIX,jiguang.cn,REJECT
#  - DOMAIN-SUFFIX,jpush.cn,REJECT
#  - DOMAIN-SUFFIX,jpush.io,REJECT
#  - DOMAIN,afd.baidu.com,REJECT
#  - DOMAIN,als.baidu.com,REJECT
  - DOMAIN,bgg.baidu.com,REJECT
#  - DOMAIN,cpro.baidustatic.com,REJECT
  - DOMAIN,feed-image.baidu.com,REJECT
  - DOMAIN,click-bes.baidu.com,REJECT
#  - DOMAIN,eclick.baidu.com,REJECT
  - DOMAIN,mobads-logs.baidu.com,REJECT
  - DOMAIN,mobads-pre-config.cdn.bcebos.com,REJECT
#  - DOMAIN,mobads.baidu.com,REJECT
  - DOMAIN,nadvideo2.baidu.com,REJECT
#  - DOMAIN,wn.pos.baidu.com,REJECT
  - DOMAIN,miniapp-ad.cdn.bcebos.com,REJECT
  - DOMAIN-SUFFIX,union.baidu.cn,REJECT
#  - DOMAIN-SUFFIX,union.baidu.com,REJECT
#  - DOMAIN,adsmind.gdtimg.com,REJECT
  - DOMAIN,huatuocode.huatuo.qq.com,REJECT
  - DOMAIN,info4.video.qq.com,REJECT
  - DOMAIN,info6.video.qq.com,REJECT
#  - DOMAIN,ios.bugly.qq.com,REJECT
  - DOMAIN,pro.bugly.qq.com,REJECT
  - DOMAIN,ios.video.mpush.qq.com,REJECT
#  - DOMAIN,otheve.beacon.qq.com,REJECT
#  - DOMAIN,pgdt.gtimg.cn,REJECT
  - DOMAIN,qzs.gdtimg.com,REJECT
  - DOMAIN,qzs.qq.com,REJECT
# - DOMAIN,rmonitor.qq.com,REJECT
#  - DOMAIN,sdk.e.qq.com,REJECT
  - DOMAIN,sdkconfig.video.qq.com,REJECT
  - DOMAIN,tmead.y.qq.com,REJECT
  - DOMAIN,tmeadbak.y.qq.com,REJECT
  - DOMAIN,tmeadcomm.y.qq.com,REJECT
  - DOMAIN,tpns.qq.com,REJECT
  - DOMAIN,wup.imtt.qq.com,REJECT
#  - DOMAIN,tpstelemetry.tencent.com,REJECT
  - DOMAIN-KEYWORD,trace.qq.com,REJECT
  - DOMAIN-KEYWORD,trace.video.qq.com,REJECT
#  - DOMAIN-SUFFIX,gdt.qq.com,REJECT
#  - DOMAIN-SUFFIX,l.qq.com,REJECT
  - DOMAIN-SUFFIX,ugdtimg.com,REJECT
  - IP-CIDR,47.110.187.87/32,REJECT,no-resolve
  - DOMAIN-SUFFIX,openinstall.io,REJECT
#  - DOMAIN,b-gtc.getui.net,REJECT
#  - DOMAIN,c-gtc.getui.net,REJECT
#  - DOMAIN,c-ido.getui.net,REJECT
#  - DOMAIN,ido.getui.net,REJECT
  - DOMAIN,ido.gepush.com,REJECT
  - DOMAIN-SUFFIX,mobileservice.cn,REJECT
#  - DOMAIN-SUFFIX,getui.com,REJECT
  - DOMAIN-SUFFIX,igexin.com,REJECT
#  - DOMAIN,cnlogs.umeng.com,REJECT
# - DOMAIN,errlog.umeng.com,REJECT
#  - DOMAIN,errnewlog.umeng.com,REJECT
#  - DOMAIN,ucc.umeng.com,REJECT
#  - DOMAIN,ulogs.umeng.com,REJECT
#  - DOMAIN,utoken.umeng.com,REJECT
#  - DOMAIN,deeplink.umeng.com,REJECT
#  - DOMAIN,aspect-upush.umeng.com,REJECT
#  - DOMAIN,plbslog.umeng.com,REJECT
#  - DOMAIN,log.umtrack.com,REJECT
#  - DOMAIN,aaid.umeng.com,REJECT
#  - DOMAIN,log.umsns.com,REJECT
  - DOMAIN,adtracker.adfunlink.com,REJECT
  - DOMAIN,sdk.tianmu.mobi,REJECT
  - DOMAIN,tracker.tianmu.mobi,REJECT
  - DOMAIN,e-u1.ubixioe.com,REJECT
  - DOMAIN,sdk-data.ubixioe.com,REJECT
  - DOMAIN,tower.ubixioe.com,REJECT
  - DOMAIN,tx-cfg-u1.ubixioe.com,REJECT
  - DOMAIN,tx-data-u1.ubixioe.com,REJECT
  - DOMAIN,ossgw.alicdn.com,REJECT
#  - DOMAIN,ems.youku.com,REJECT
  - DOMAIN,hudong.alicdn.com,REJECT
  - DOMAIN,et.tanx.com,REJECT
#  - DOMAIN,df.tanx.com,REJECT
#  - DOMAIN,beacon-api.aliyuncs.com,REJECT
#  - DOMAIN,adash.man.aliyuncs.com,REJECT
#  - DOMAIN,applog.uc.cn,REJECT
  - AND,((DOMAIN-KEYWORD,adash),(DOMAIN-SUFFIX,ut.taobao.com)),REJECT
#  - DOMAIN,nex.163.com,REJECT
  - DOMAIN,iad.g.163.com,REJECT
#  - DOMAIN,adx-bj.anythinktech.com,REJECT
#  - DOMAIN,api.anythinktech.com,REJECT
#  - DOMAIN,tk.anythinktech.com,REJECT
#  - DOMAIN,da.anythinktech.com,REJECT
  - DOMAIN,gorgon.youdao.com,REJECT
#  - DOMAIN,sdkconfig.ad.xiaomi.com,REJECT
  - DOMAIN,al-log.d.meituan.net,REJECT
  - DOMAIN,babel-statistics-android.d.meituan.net,REJECT
  - DOMAIN,maplocatesdksnapshot.d.meituan.net,REJECT
  - DOMAIN,metrics-picture.d.meituan.net,REJECT
  - DOMAIN,route-stats.d.meituan.net,REJECT
  - DOMAIN,dsp-x.jd.com,REJECT
  - DOMAIN,im-x.jd.com,REJECT
  - DOMAIN,xlog.jd.com,REJECT
  - DOMAIN,janapi.jd.com,REJECT
#  - DOMAIN,api.mosspf.com,REJECT
#  - DOMAIN,da.mosspf.com,REJECT
  - DOMAIN,mores.toponad.com,REJECT
#  - DOMAIN,api.toponadss.com,REJECT
#  - DOMAIN,da.toponadss.com,REJECT
#  - DOMAIN,tk.toponadss.com,REJECT
#  - DOMAIN,adx-os.toponadss.com,REJECT
  - DOMAIN-SUFFIX,motowoo.com,REJECT
  - DOMAIN,guide2.bianxianmao.com,REJECT
  - DOMAIN,caid.adintl.cn,REJECT
  - DOMAIN,sv.adintl.cn,REJECT
  - DOMAIN,v.adintl.cn,REJECT
  - DOMAIN,oss.cdn.adintl.cn,REJECT
  - DOMAIN,adx.adtaipo.com,REJECT
  - DOMAIN,adx.yixin.im,REJECT
  - DOMAIN,adx.kuaiyiad.com,REJECT
  - DOMAIN,adreport.adtianmai.com,REJECT
  - DOMAIN,adxapi.readgps.com,REJECT
  - DOMAIN,t.fanglinad.com,REJECT
  - DOMAIN,trk1.17admob.com,REJECT
  - DOMAIN,nfy.slyxmobi.com,REJECT
  - DOMAIN,api.mobrtb.com,REJECT
  - DOMAIN,ssp.maplehaze.cn,REJECT
  - DOMAIN-SUFFIX,lnk0.com,REJECT
  - DOMAIN-SUFFIX,bridgeoos.com,REJECT
  - DOMAIN,ad-evods.tianya.tv,REJECT
  - DOMAIN,adx.tuia.cn,REJECT
  - DOMAIN-SUFFIX,66mobi.com,REJECT
  - DOMAIN,o33249.ingest.sentry.io,REJECT
#  - DOMAIN,events.statsigapi.net,REJECT
#  - DOMAIN,api.mixpanel.com,REJECT
#  - DOMAIN,browser-intake-datadoghq.com,REJECT
  - GEOSITE,category-ads-all,REJECT
unified-delay: true
find-process-mode: always