# 自用 Clash 规则配置
ruleset=DIRECT,rules/blackmatrix7/ios_rule_script/rule/Clash/ChinaMax/ChinaMax.list
ruleset=DIRECT,rules/blackmatrix7/ios_rule_script/rule/Clash/Apple/Apple.list
ruleset=选,rules/blackmatrix7/ios_rule_script/rule/Clash/Proxy/Proxy.list
ruleset=选,[]FINAL

custom_proxy_group=选`select`.*

# Clash 订阅链接：https://api.dler.io/sub?target=clash&url=替换成你的订阅&config=https://raw.githubusercontent.com/MingdeCZ/OutSide-Reborn/main/Clash/Configs/test.ini&exclude=%E5%88%B0%E6%9C%9F%7C%E5%89%A9%E4%BD%99%7C%E5%AE%98%E7%BD%91%7C%E6%9C%BA%E5%9C%BA%7C%E6%9B%B4%E6%96%B0&emoji=true
